In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_496.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_5003.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_5942.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_6258.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_2162.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_8021.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_7693.jpeg
/kaggle/input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front/cast_ok_0_4010.jpeg
/kaggle/input/rea

In [2]:
import tensorflow as tf#for back-end

from tensorflow import keras#for back-end

from tensorflow.keras import Sequential#for sequentiality of layers

from tensorflow.keras.layers import Dense,Flatten,Conv2D,Dropout,MaxPool2D #for layers,operations and parameters

from tensorflow.keras.preprocessing.image import img_to_array  #to correctly fit the input into the sample data frame by using matrix

import cv2  #image lib

from PIL import Image #image lib

from tensorflow.keras import optimizers    # for graph optimation in training

In [6]:
import matplotlib.pyplot as plt

img_height=64

img_width=64

defective=os.listdir("../input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/def_front")

ok=os.listdir("../input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front")


In [7]:
label=[]

data=[]
i=0
#iterating through imgs directory
for img in defective :
    try :
        #reading each image
        img_read=plt.imread("../input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/def_front"+"/"+img)
        
        #resizing the images
        img_resize=cv2.resize(img_read,(img_height,img_width))
        
        #converting img to array
        img_array=img_to_array(img_resize)
        
        #taking img data
        data.append(img_array)
        
        if i<=10 :
            print(img_array)
        
        #taking ok or no values
        label.append(0)
    
    except :
        None
    i+=1
for img in ok :
    try :
        #reading each image
        img_read=plt.imread("../input/real-life-industrial-dataset-of-casting-product/casting_512x512/casting_512x512/ok_front"+"/"+img)
        
        #resizing the images
        img_resize=cv2.resize(img_read,(img_height,img_width))
        
        #converting img to array
        img_array=img_to_array(img_resize)
        
        #taking img data
        data.append(img_array)
        
        #taking ok or no values
        label.append(1)
    
    except :
        None

[[[181. 181. 181.]
  [181. 181. 181.]
  [178. 178. 178.]
  ...
  [186. 186. 186.]
  [184. 184. 184.]
  [179. 179. 179.]]

 [[179. 179. 179.]
  [177. 177. 177.]
  [179. 179. 179.]
  ...
  [183. 183. 183.]
  [182. 182. 182.]
  [182. 182. 182.]]

 [[178. 178. 178.]
  [178. 178. 178.]
  [177. 177. 177.]
  ...
  [180. 180. 180.]
  [181. 181. 181.]
  [181. 181. 181.]]

 ...

 [[141. 141. 141.]
  [141. 141. 141.]
  [139. 139. 139.]
  ...
  [151. 151. 151.]
  [147. 147. 147.]
  [147. 147. 147.]]

 [[142. 142. 142.]
  [140. 140. 140.]
  [145. 145. 145.]
  ...
  [144. 144. 144.]
  [149. 149. 149.]
  [146. 146. 146.]]

 [[142. 142. 142.]
  [140. 140. 140.]
  [145. 145. 145.]
  ...
  [144. 144. 144.]
  [149. 149. 149.]
  [146. 146. 146.]]]
[[[169. 169. 169.]
  [171. 171. 171.]
  [172. 172. 172.]
  ...
  [158. 158. 158.]
  [157. 157. 157.]
  [157. 157. 157.]]

 [[171. 171. 171.]
  [174. 174. 174.]
  [171. 171. 171.]
  ...
  [155. 155. 155.]
  [155. 155. 155.]
  [156. 156. 156.]]

 [[173. 173. 173.]

In [8]:
#converting data into numpy arrays

img_data=np.array(data)

label=np.array(label)
img_data=img_data/255

# Number of imgaes in first row print(img_data.shape[0])

#label array print(label)


In [9]:
#storing img data into x to get shuffle it
x=np.arange(img_data.shape[0])

#shuffling x
np.random.shuffle(x)

#mapping the original data with shuffled data
img_data=img_data[x]

label=label[x]

print(img_data.shape)
print(label)

(1300, 64, 64, 3)
[1 0 1 ... 0 0 0]


In [10]:
#for traimning and testing
from sklearn.model_selection import train_test_split

#80 are for training and 20 are for testing in every 101 samples
x_train,x_test,y_train,y_test=train_test_split(img_data,label,test_size=0.2,random_state=101)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(1040, 64, 64, 3) (260, 64, 64, 3) (1040,) (260,)


In [11]:

#INPUT LAYER

#creating model
model=Sequential()

#CNN Usage

#for an input layer
model.add(Conv2D(16,(3,3),input_shape=(img_height,img_width,3),activation='relu'))

#normalization
model.add(MaxPool2D(2,2))

model.add(Dropout(0.2))

#Brings data from 3x3 to one dimension
model.add(Flatten())


#HIDDEN LAYERS

model.add(Dense(64,activation='relu'))

model.add(Dropout(0.5))

#sigmoid is a logistic function----->0 or 1 as output
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 62, 16)        448       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 31, 31, 16)        0         
_________________________________________________________________
dropout (Dropout)            (None, 31, 31, 16)        0         
_________________________________________________________________
flatten (Flatten)            (None, 15376)             0         
_________________________________________________________________
dense (Dense)                (None, 64)                984128    
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6

In [14]:
#compiling model
model.compile(optimizer='adam',loss=tf.keras.losses.BinaryCrossentropy(),metrics=['accuracy'])

#model.evaluate(x_test,y_test,batch_size=128,verbose=1)
model.fit(x_train, y_train, batch_size=50, epochs=20)

Epoch 1/20
21/21 [==============================] - 2s 50ms/step - loss: 0.6195 - accuracy: 0.6523
Epoch 2/20
21/21 [==============================] - 1s 50ms/step - loss: 0.6017 - accuracy: 0.6275
Epoch 3/20
21/21 [==============================] - 1s 50ms/step - loss: 0.5573 - accuracy: 0.6785
Epoch 4/20
21/21 [==============================] - 1s 49ms/step - loss: 0.5518 - accuracy: 0.6592
Epoch 5/20
21/21 [==============================] - 1s 47ms/step - loss: 0.5198 - accuracy: 0.7290
Epoch 6/20
21/21 [==============================] - 1s 52ms/step - loss: 0.5067 - accuracy: 0.7334
Epoch 7/20
21/21 [==============================] - 1s 56ms/step - loss: 0.4828 - accuracy: 0.7654
Epoch 8/20
21/21 [==============================] - 1s 49ms/step - loss: 0.4949 - accuracy: 0.7445
Epoch 9/20
21/21 [==============================] - 1s 52ms/step - loss: 0.4639 - accuracy: 0.7734
Epoch 10/20
21/21 [==============================] - 1s 47ms/step - loss: 0.4673 - accuracy: 0.7625
Epoch 11/

In [15]:

#result=model.fit(x_train,y_train,batch_size=128,epochs=40)
model.fit(x_train,y_train)

33/33 [==============================] - 1s 34ms/step - loss: 0.3598 - accuracy: 0.8231
